Task: Cleanup tests.
Schema's have changed alot since some of these tests
were written and they weren't updated with the schemas.

At start, Ran 12 tests, FAILED (errors=14).

Errors:
AttributeError: 'OntarioThemePlugin' object has no attribute 'create_package_schema'
SchemingException: preset 'fluent_core_translated' not defined
IOError: [Errno 2] No such file or directory: '/home/cody/ckan/lib/default/src/ckan/ckanext/ckanext-ontario_theme/ckanext/ontario_theme/tests/../licences.json'
Exception: Cannot unload plugin `ontario_theme`

Remove IDataSetForm from plugin as this is no longer used (or could have set to inherit=True or create empty method).
Add config settings to test.ini to fix the SchemingException.
Change licences.json path to new path.

Update package dict for test_create_dataset.py.
Remove obsolete tests for test_create_dataset.py.

Update package dict for test_helpers.py.

Update package dict for test_resource_upload.py.

Update package dict for test_updated_dataset.py.
Remove obsolete tests for test_update_dataset.py.

At end, Ran 18 tests, OK